const Double = require("@mongoosejs/double/lib");
const mongoose = require("mongoose");

const chargedUpSchema = mongoose.Schema(
	{
		editHistory: Array,
		competition: { type: String, required: true },
		matchNumber: { type: Number, required: true },
		teamNumber: { type: Number, required: true },
		teamName: { type: String, required: true },
		RPEarned: Array,
		totalRP: Number,
		autoPeriod: {
			botScore: Number,
			botCones: Number,
			botCubes: Number,
			midScore: Number,
			midCones: Number,
			midCubes: Number,
			topScore: Number,
			topCones: Number,
			topCubes: Number,
			totalScore: Number,
			totalCones: Number,
			totalCubes: Number,
			coneRate: Double,
			cubeRate: Double,
		},
		teleopPeriod: {
			botScore: Number,
			botCones: Number,
			botCubes: Number,
			midScore: Number,
			midCones: Number,
			midCubes: Number,
			topScore: Number,
			topCones: Number,
			topCubes: Number,
			totalScore: Number,
			totalCones: Number,
			totalCubes: Number,
			coneRate: Double,
			cubeRate: Double,
		},
		coneRate: Number,
		cubeRate: Number,
		linkScore: Number,
		autoDock: Boolean,
		autoEngage: Boolean,
		teleopDock: Boolean,
		teleopEngage: Boolean,
		parked: Boolean,
		isDefensive: Boolean,
		chargeStation: Number,
		didBreak: Boolean,
		penaltyCount: Number,
		score: { type: Number, required: true },
		won: { type: Boolean, required: true },
		tied: { type: Boolean, required: true },
		comments: String,
	},
	{
		timestamps: true,
	}
);

module.exports = global.scoutingDb.model("ChargedUp", chargedUpSchema);
