---
name: "ci / prod"

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v3
            - name: Push to Dokku
              uses: dokku/github-action@master
              with:
                  git_remote_url: ssh://dokku@146.190.15.139:22/api
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
