---
name: "ci / staging"

on:
    push:
        branches:
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            deployments: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push container image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: ghcr.io/frc-emotion/staging-api:amd-latest
            - name: Connect to server and trigger redeploy of docker containers
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: "team2658.org"
                  username: "root"
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                      docker logout ghcr.io
                      docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
                      docker pull ghcr.io/frc-emotion/staging-api:amd-latest
                      docker stop api-staging
                      docker rm api-staging
                      docker run -d --name api-staging -e NODE_ENV=development -e API_URL='' -e MONGO_URI_DEV=${{secrets.MONGO_URI_DEV}} -e JWT_SECRET=${{secrets.JWT_SECRET}} -e TBA_KEY=${{secrets.TBA_KEY}} -e RESEND_KEY=${{secrets.RESEND_KEY}} -e PORT=3000 -p 5555:3000 ghcr.io/frc-emotion/staging-api:amd-latest
                      docker logout ghcr.io
